### ISSUE TITLE
Is there any docker environment for the Jetson that will work with this?

### ISSUE THREAD

**Issue by jpcookie** [bricewalker/Hey-Jetson#86]
I've been getting problems with Keras regarding generic utility functions and other problems of modules when I try to adapt my own Jetson to get this to work.

**Comment by bricewalker** [comment]
I have not prepared any containers, but you are free to build one yourself. By viewing the requirements.txt files, the conda environment yaml file, and the package imports in the notebooks and scripts, you can determine the required packages and build an environment with your tool of choice. It will take some problem solving and due to the lack of support, you should seek to install packages with 'sudo apt-get install python3-<libraryname>' whenever possible. There may be some packages where this is the only option to install. I do not recall what packages I installed with this method, and I no longer own at Jetson so I cannot help you further. Good luck.
